 const constants = {
  FETCH_ALL_HOTELS:"FETCH_ALL_HOTELS",
  ADD_HOTELS:"ADD_HOTELS",
  FETCH_ALL_CATEGORIES:"FETCH_ALL_CATEGORIES",
  FETCH_ROOMTYPES:"FETCH_ROOMTYPES",
  FETCH_HOTEL_BY_CATEGORY:"FETCH_HOTEL_BY_CATEGORY",
  FETCH_HOTELS_BY_CATGORIES:'FETCH_HOTELS_BY_CATGORIES',
  ADD_ERROR:'ADD_ERROR',
  CLEAR_ERROR:'CLEAR_ERROR',
  ADD_STATUS:"ADD_STATUS",
CLEAR_STATUS:"CLEAR_STATUS",
   FETCH_HOTEL_BY_ROOMTYPE:'FETCH_HOTEL_BY_ROOMTYPE',
   FETCH_ALL_HOTELS_BY_ROOMTYPE:'FETCH_ALL_HOTELS_BY_ROOMTYPE',
   FETCH_ALL_TRANSPORT:'FETCH_ALL_TRANSPORT',
   FETCH_HOTEL_BY_TRANSPORT:'FETCH_HOTEL_BY_TRANSPORT'
};


export default constants;
